package com.splendordashboard;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.hardware.*;import android.location.*;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity implements LocationListener, SensorEventListener {
    DashboardView view; AppPrefs prefs; LocationManager lm; SensorManager sm; Sensor rotation; float heading=0; boolean haveHeading=false; boolean demo=false; long lastLoc=0; float smoothSpeed=0; float lastLat=0,lastLon=0; boolean haveLoc=false; float accuracy=Float.NaN; BatteryReceiver batteryReceiver;
    long tripStart=0, movingMs=0; float tripKm=0, avgSpeed=0,maxSpeed=0; boolean tripRunning=false,tripPaused=false; long lastTripTick=0;
    @Override public void onCreate(Bundle b){super.onCreate(b); setRequestedOrientation(0); prefs=new AppPrefs(this); applyWindow(); loadTrip(); view=new DashboardView(this); setContentView(view); if(Build.VERSION.SDK_INT>=33 && checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED) requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},43); initSensors(); initLocation(); registerBattery(); if(prefs.autoTrip()) startTrip();}
    void applyWindow(){getWindow().setFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON,WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON); if(!prefs.awake())getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON); if(prefs.fullscreen()) getWindow().getDecorView().setSystemUiVisibility(5894);}
    void initSensors(){sm=(SensorManager)getSystemService(SENSOR_SERVICE); rotation=sm.getDefaultSensor(Sensor.TYPE_ROTATION_VECTOR); if(rotation==null)rotation=sm.getDefaultSensor(Sensor.TYPE_MAGNETIC_FIELD); if(rotation!=null)sm.registerListener(this,rotation,SensorManager.SENSOR_DELAY_UI);}
    void initLocation(){ if(Build.VERSION.SDK_INT>=23 && checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},42);return;} startLocation(); }
    void startLocation(){ try{lm=(LocationManager)getSystemService(LOCATION_SERVICE); if(!lm.isProviderEnabled(LocationManager.GPS_PROVIDER)){view.invalidate();return;} lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,500,1,this,Looper.getMainLooper());}catch(Exception e){}}
    void stopLocation(){try{if(lm!=null)lm.removeUpdates(this);}catch(Exception ignored){}}
    @Override protected void onResume(){super.onResume(); applyWindow(); if(prefs.demo()){demo=true;} if(Build.VERSION.SDK_INT<23||checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED)startLocation(); if(rotation!=null)sm.registerListener(this,rotation,SensorManager.SENSOR_DELAY_UI);}
    @Override protected void onPause(){super.onPause(); stopLocation(); if(sm!=null)sm.unregisterListener(this); saveTrip();}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g); if(r==42 && g.length>0 && g[0]==PackageManager.PERMISSION_GRANTED)startLocation(); view.invalidate();}
    void registerBattery(){batteryReceiver=new BatteryReceiver(view); if(Build.VERSION.SDK_INT>=33) registerReceiver(batteryReceiver,new IntentFilter(Intent.ACTION_BATTERY_CHANGED),Context.RECEIVER_NOT_EXPORTED); else registerReceiver(batteryReceiver,new IntentFilter(Intent.ACTION_BATTERY_CHANGED));}
    @Override protected void onDestroy(){super.onDestroy();try{unregisterReceiver(batteryReceiver);}catch(Exception ignored){} stopLocation();if(sm!=null)sm.unregisterListener(this);saveTrip();}
    @Override public void onLocationChanged(Location l){if(l==null)return; accuracy=l.hasAccuracy()?l.getAccuracy():Float.NaN; float raw=l.hasSpeed()?l.getSpeed()*3.6f:0; if(raw<0||raw>240)return; if(lastLoc>0){long dt=l.getTime()-lastLoc;if(dt>0&&dt<15000&&haveLoc){float d=distance(lastLat,lastLon,(float)l.getLatitude(),(float)l.getLongitude());float implied=d/(dt/3600000f);if(implied>240)return;}} lastLoc=l.getTime(); lastLat=(float)l.getLatitude();lastLon=(float)l.getLongitude();haveLoc=true; if(raw<2)raw=0; smoothSpeed=smoothSpeed*0.72f+raw*0.28f; if(Math.abs(smoothSpeed)<0.5)smoothSpeed=0; if(tripRunning&&!tripPaused){if(lastTripTick>0){long dt=System.currentTimeMillis()-lastTripTick;movingMs+=dt;if(smoothSpeed>1){tripKm+=smoothSpeed*dt/3600000f;maxSpeed=Math.max(maxSpeed,smoothSpeed);}} lastTripTick=System.currentTimeMillis();} view.invalidate();}
    float distance(float a,float b,float c,float d){double R=6371;double x=Math.toRadians(c-a),y=Math.toRadians(d-b);double q=Math.sin(x/2)*Math.sin(x/2)+Math.cos(Math.toRadians(a))*Math.cos(Math.toRadians(c))*Math.sin(y/2)*Math.sin(y/2);return(float)(R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q)));}
    float speed(){return demo?prefs.demoSpeed():smoothSpeed;}
    void startTrip(){tripRunning=true;tripPaused=false;lastTripTick=System.currentTimeMillis();saveTrip();view.invalidate();} void pauseTrip(){if(tripRunning&&!tripPaused){tickTrip();tripPaused=true;}else if(tripRunning){tripPaused=false;lastTripTick=System.currentTimeMillis();}view.invalidate();saveTrip();} void tickTrip(){if(tripRunning&&!tripPaused&&lastTripTick>0){long dt=System.currentTimeMillis()-lastTripTick;movingMs+=dt;float s=speed();if(s>1){tripKm+=s*dt/3600000f;maxSpeed=Math.max(maxSpeed,s);}lastTripTick=System.currentTimeMillis();}}
    void resetTrip(){tripRunning=false;tripPaused=false;tripKm=0;movingMs=0;maxSpeed=0;avgSpeed=0;lastTripTick=0;saveTrip();view.invalidate();}
    void saveTrip(){getPreferences(0).edit().putFloat("km",tripKm).putLong("ms",movingMs).putFloat("max",maxSpeed).putBoolean("run",tripRunning).putBoolean("pause",tripPaused).apply();}
    void loadTrip(){SharedPreferences p=getPreferences(0);tripKm=p.getFloat("km",0);movingMs=p.getLong("ms",0);maxSpeed=p.getFloat("max",0);tripRunning=p.getBoolean("run",false);tripPaused=p.getBoolean("pause",false);if(tripRunning)lastTripTick=System.currentTimeMillis();}
    void openNav(){Intent i=new Intent(Intent.ACTION_VIEW, Uri.parse("google.navigation:q=0,0"));if(i.resolveActivity(getPackageManager())!=null)startActivity(i);else Toast.makeText(this,"Navigation app not installed.",Toast.LENGTH_SHORT).show();}
    void openSettings(){startActivity(new Intent(this,SettingsActivity.class));}
    void openDiagnostics(){startActivity(new Intent(this,DiagnosticsActivity.class));}
    void refuel(){getPreferences(0).edit().putLong("refuel",System.currentTimeMillis()).putFloat("refuelTripKm",tripKm).apply();Toast.makeText(this,"Tank refilled • estimated range reset",Toast.LENGTH_SHORT).show();view.invalidate();}
    class DashboardView extends View {Paint p=new Paint(3); RectF r=new RectF(); public DashboardView(Context c){super(c);p.setTypeface(Typeface.create("sans",Typeface.NORMAL));setFocusable(true);}
      void txt(Canvas c,String s,float x,float y,float size,int color,Paint.Align a){p.setTextSize(size);p.setColor(color);p.setTextAlign(a);p.setTypeface(Typeface.create("sans",Typeface.NORMAL));c.drawText(s,x,y,p);} void bold(Canvas c,String s,float x,float y,float size,int color,Paint.Align a){p.setTextSize(size);p.setColor(color);p.setTextAlign(a);p.setTypeface(Typeface.create("sans",Typeface.BOLD));c.drawText(s,x,y,p);}
      @Override protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),h=getHeight();boolean day=prefs.theme()==1 || (prefs.theme()==0 && (java.time.LocalTime.now().getHour()>=7 && java.time.LocalTime.now().getHour()<19)); c.drawColor(day?Color.rgb(242,245,246):Color.rgb(5,7,8)); int white=day?Color.rgb(18,22,24):Color.rgb(245,247,248),mut=day?Color.rgb(85,95,102):Color.rgb(140,150,158),acc=Color.rgb(36,154,190),danger=Color.rgb(205,55,55),panel=day?Color.rgb(232,236,238):Color.rgb(17,22,26);txt(c,"GPS "+(haveLoc?"●":"○"),24,34,18,haveLoc?acc:danger,Paint.Align.LEFT);txt(c,haveLoc?String.format(Locale.US,"%.0f m",accuracy):"Searching…",24,58,13,mut,Paint.Align.LEFT);txt(c,new java.text.SimpleDateFormat("hh:mm a",Locale.US).format(new Date()),w/2f,35,22,white,Paint.Align.CENTER);txt(c,"BAT "+(batteryReceiver==null?"--":batteryReceiver.level)+"%"+(batteryReceiver!=null&&batteryReceiver.charging?"  USB":""),w-24,35,16,batteryReceiver!=null&&batteryReceiver.charging?acc:mut,Paint.Align.RIGHT);
        float cx=w*.50f,cy=h*.48f,rad=Math.min(w,h)*.33f;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(Color.rgb(42,51,57));c.drawArc(new RectF(cx-rad,cy-rad,cx+rad,cy+rad),-225,270,false,p);float sp=Math.min(speed(),prefs.gaugeMax());float sweep=270*sp/prefs.gaugeMax();p.setColor(sp>prefs.gaugeMax()*.85?danger:acc);p.setStrokeWidth(8);c.drawArc(new RectF(cx-rad,cy-rad,cx+rad,cy+rad),-225,sweep,false,p);p.setStyle(Paint.Style.FILL);bold(c,String.format(Locale.US,"%.0f",speed()),cx,cy+18,Math.min(w,h)*.17f,white,Paint.Align.CENTER);txt(c,"km/h"+(demo?"  • DEMO":""),cx,cy+50,20,demo?Color.rgb(255,209,102):mut,Paint.Align.CENTER);
        int y=h-112; p.setColor(panel);c.drawRoundRect(new RectF(18,y-30,w-18,y+34),18,18,p);txt(c,String.format(Locale.US,"TRIP %.1f km",tripKm),35,y+5,15,white,Paint.Align.LEFT); if(prefs.showCompass()) txt(c,haveHeading?String.format(Locale.US,"%s %.0f°",cardinal(heading),heading):"COMPASS —",w*.83f,y+5,15,white,Paint.Align.CENTER);txt(c,"AVG "+(movingMs>0?String.format(Locale.US,"%.0f",tripKm/(movingMs/3600000f)):"0"),w*.30f,y+5,15,white,Paint.Align.CENTER);txt(c,String.format(Locale.US,"MAX %.0f",maxSpeed),w*.47f,y+5,15,white,Paint.Align.CENTER);txt(c,String.format(Locale.US,"%02d:%02d:%02d",movingMs/3600000,(movingMs/60000)%60,(movingMs/1000)%60),w*.67f,y+5,15,white,Paint.Align.CENTER);txt(c,"RANGE "+String.format(Locale.US,"%.0f km",estimatedRange()),w-35,y+5,15,acc,Paint.Align.RIGHT);
        float by=h-54;button(c,20,by,120,by+42,"NAV",acc);button(c,132,by,242,by+42,tripRunning?(tripPaused?"RESUME":"PAUSE"):"START",white);button(c,254,by,370,by+42,"REFUEL",Color.rgb(255,209,102));button(c,w-220,by,w-112,by+42,"RESET",danger);button(c,w-100,by,w-20,by+42,"SET",white); }
      void button(Canvas c,float l,float t,float rr,float b,String s,int col){p.setColor(Color.rgb(20,27,31));c.drawRoundRect(new RectF(l,t,rr,b),12,12,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(col);c.drawRoundRect(new RectF(l,t,rr,b),12,12,p);p.setStyle(Paint.Style.FILL);bold(c,s,(l+rr)/2,t+27,13,col,Paint.Align.CENTER);}
      String cardinal(float d){String[] c={"N","NE","E","SE","S","SW","W","NW"};return c[(int)Math.round(d/45f)%8];}
      float estimatedRange(){float base=Math.min(prefs.maxRange(),prefs.tank()*prefs.mileage());float refuelAt=getPreferences(0).getFloat("refuelTripKm",0);float used=Math.max(0,tripKm-refuelAt);return Math.max(0,base-used);} 
      @Override public boolean onTouchEvent(android.view.MotionEvent e){if(e.getAction()!=1)return true;float x=e.getX(),y=e.getY();if(y>getHeight()-75){if(x<125)openNav();else if(x<245) {if(tripRunning)pauseTrip();else startTrip();}else if(x<380)refuel();else if(x<getWidth()-105){new AlertDialog.Builder(MainActivity.this).setTitle("Reset trip?").setMessage("This resets trip distance, time and max speed only.").setNegativeButton("Cancel",null).setPositiveButton("RESET",(d,w)->resetTrip()).show();}else openSettings();return true;} if(y<75&&x<120)openDiagnostics();return true;}
    }
    public class BatteryReceiver extends BroadcastReceiver {int level=0;boolean charging=false;View v;BatteryReceiver(View v){this.v=v;}public void onReceive(Context c,Intent i){int l=i.getIntExtra(BatteryManager.EXTRA_LEVEL,-1),s=i.getIntExtra(BatteryManager.EXTRA_STATUS,-1);level=l;charging=s==BatteryManager.BATTERY_STATUS_CHARGING||s==BatteryManager.BATTERY_STATUS_FULL;if(v!=null)v.invalidate();}}
    @Override public void onSensorChanged(SensorEvent e){if(e.sensor.getType()==Sensor.TYPE_ROTATION_VECTOR){float[] R=new float[9],o=new float[3];SensorManager.getRotationMatrixFromVector(R,e.values);SensorManager.getOrientation(R,o);float deg=(float)Math.toDegrees(o[0]);if(deg<0)deg+=360;heading=heading*.8f+deg*.2f;haveHeading=true;view.invalidate();}else if(e.sensor.getType()==Sensor.TYPE_MAGNETIC_FIELD){haveHeading=true;}}
    @Override public void onAccuracyChanged(Sensor s,int a){}
}